name: openapi_freezed_dio_builder
description: Generate models and API classes based on an OpenAPI document using Freezed and Dio.
version: 0.9.4
homepage: https://github.com/jonasbark/openapi_freezed_dio_builder/tree/master/packages/openapi_freezed_dio_builder

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  logging: ^1.0.1
  meta: ">=1.5.0 <2.0.0"
  openapi_base: ^1.0.2+2
  path: ^1.8.0
  dart_style: ">=2.0.1 <3.0.0"
  code_builder: ">=4.0.0 <5.0.0"
  build: ">=2.0.2 <3.0.0"
  source_gen: ">=1.0.2 <2.0.0"
  recase: ^4.0.0
  open_api_forked: ^3.0.0+5
  collection: ^1.15.0
  built_collection: ^5.1.1
  quiver: ^3.0.1+1
  yaml: ^3.1.0
  json_annotation: ">=4.0.1 <6.0.0"

dev_dependencies:
  pedantic: ^1.11.1

#dependency_overrides:
#  openapi_base:
#    path: ../openapi_base
#  open_api_forked:
#    path: ../../deps/open-api-dart
#  codable_forked:
#    path: ../../deps/dart-codable
